name: Haddock
# Test documentation: haddock, user-manual.
# Since `stack haddock` compiles Agda but `cabal haddock` does
# not, this test is faster using `BUILD=CABAL` [IssueÂ #2188].
on:
  push:
    paths:
    - 'src/**.hs'
    - '.github/workflows/haddock.yml'
  pull_request:
    paths:
    - 'src/**.hs'
    - '.github/workflows/haddock.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.1'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal new-update
        cabal new-install alex happy
        cabal new-install --dependencies-only -fenable-cluster-counting --force-reinstalls --disable-library-profiling
    # Testing Haddock [Issue 1773]
    - name: Build
      run: |
        cabal new-configure -fenable-cluster-counting --enable-tests
        cabal new-haddock
