name: Nightly build

on:
  push:
    paths:
    - '.github/workflows/nightly.yml'

  schedule:
    #Â Run every day at 0400.
    - cron: '0 04 * * *'

jobs:
  Ubuntu:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ghc-ver: [8.10.2]
    env:
      ARGS: "--stack-yaml stack-${{ matrix.ghc-ver }}.yaml --no-terminal --system-ghc"
      FLAGS: "--flag Agda:enable-cluster-counting"

    steps:
    - uses: actions/checkout@v2.3.2
      with:
        submodules: recursive

    - uses: actions/setup-haskell@v1.1.3
      with:
        ghc-version: ${{ matrix.ghc-ver }}

    - name: Build dependencies
      run: |
        stack build ${ARGS} ${FLAGS} --only-dependencies

    - name: Build Agda
      run: |
        stack build ${ARGS} ${FLAGS}

    - name: Pack artifacts
      run: |
        mkdir -p upload/bin
        cp -av .stack-work/dist/x86_64-linux/**/build/agda/agda upload/bin
        cp -av .stack-work/dist/x86_64-linux/**/build/agda-mode/agda-mode upload/bin
        cp -avr src/data upload
        cp -av .github/*.sh upload

    - uses: actions/upload-artifact@v2.0.1
      with:
        name: agda-linux-${{ github.sha }}
        path: upload

  macOS:
    runs-on: macos-latest

    strategy:
      matrix:
        ghc-ver: [8.10.2]

    env:
      ARGS: "--stack-yaml stack-${{ matrix.ghc-ver }}.yaml --no-terminal --system-ghc"
      FLAGS: "--flag Agda:enable-cluster-counting"

    steps:
    - uses: actions/checkout@v2.3.2
      with:
        submodules: recursive

    - name: Install stack
      run: |
        brew install haskell-stack
        stack update --stack-yaml stack-${{ matrix.ghc-ver }}.yaml --system-ghc

    - name: Configure text-icu
      run: |
        printf "extra-lib-dirs:\n - /usr/local/opt/icu4c/lib\nextra-include-dirs:\n - /usr/local/opt/icu4c/include\n" > ~/.stack/config.yaml

    - name: Build dependencies
      run: |
        stack build ${ARGS} ${FLAGS} --only-dependencies

    - name: Build Agda
      run: |
        stack build ${ARGS} ${FLAGS}

    - name: Pack artifacts
      run: |
        mkdir -p upload/bin
        cp -av .stack-work/dist/x86_64-osx/**/build/agda/agda upload/bin
        cp -av .stack-work/dist/x86_64-osx/**/build/agda-mode/agda-mode upload/bin
        cp -av src/data upload
        cp -av .github/*.sh upload

    - uses: actions/upload-artifact@v2.0.1
      with:
        name: agda-macOS-${{ github.sha }}
        path: upload

  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        # We can not use 8.10.2 because #4965.
        ghc-ver: [8.10.1]
        icu-ver: [65.1-1]

    env:
      ICU_FILE: "mingw-w64-x86_64-icu-${{ matrix.icu-ver }}-any.pkg.tar.xz"

    steps:
    - uses: actions/checkout@v2.3.2
      with:
        submodules: recursive

    - name: Download ICU ${{ matrix.icu-ver }}
      run: |
        stack --compiler ghc-${{ matrix.ghc-ver }} exec -- wget -q http://repo.msys2.org/mingw/x86_64/${env:ICU_FILE}

    - name: Install text-icu ${{ matrix.icu-ver }}
      run: |
        stack --compiler ghc-${{ matrix.ghc-ver }} exec -- pacman -U --noconfirm ${env:ICU_FILE}
        stack build --compiler ghc-${{ matrix.ghc-ver }} text-icu

    # See comment in .github/workflows/stack.yml
    - name: Build dependencies
      run: |
        stack build --stack-yaml=stack-${{ matrix.ghc-ver }}.yaml --no-terminal --fast --flag Agda:enable-cluster-counting --only-dependencies

    - name: Build agda
      run: |
        stack build --stack-yaml=stack-${{ matrix.ghc-ver }}.yaml --no-terminal --fast --flag Agda:enable-cluster-counting

    - name: Pack artifacts
      shell: bash
      run: |
        mkdir -p upload/bin
        cp -av ~/AppData/Local/Programs/stack/x86_64-windows/msys2-20180531/mingw64/bin/*.dll upload/bin
        cp -av .stack-work/install/**/bin/agda.exe upload/bin
        cp -av .stack-work/install/**/bin/agda-mode.exe upload/bin
        cp -avr src/data upload
        cp -av .github/*.bat upload

    - uses: actions/upload-artifact@v2.0.1
      with:
        name: agda-windows-${{ github.sha }}
        path: upload
