name: Whitespace
on: [push, pull_request]

jobs:
  check:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, '[github skip]')
      && !contains(github.event.head_commit.message, '[skip github]')

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ghc-ver: [8.10.3]
        stack-ver: [2.5.1]

    steps:
    - uses: actions/checkout@v2
    - name: Check the commit SHA of submodule fix-whitespace
      run: |
        echo fw-sha=`git submodule status -- src/fix-whitespace | git submodule status -- src/fix-whitespace | cut -c 2- | cut -d " " -f 1`  >> $GITHUB_ENV

    - uses: actions/cache@v2
      name: Cache the binary
      id: cache
      with:
        path: "~/.local/bin"
        key: fix-whitespace-${{ env.fw-sha }}

    - uses: haskell/actions/setup@v1
      if: ${{ !steps.cache.outputs.cache-hit }}
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        stack-version: ${{ matrix.stack-ver }}
        enable-stack: true

    - name: Install fix-whitespace
      if: ${{ !steps.cache.outputs.cache-hit }}
      run: |
        git submodule update --init -- src/fix-whitespace/
        stack install fix-whitespace --stack-yaml stack-${{ matrix.ghc-ver }}.yaml --system-ghc
        strip $HOME/.local/bin/fix-whitespace

    - name: Check the whitespace issue
      run: |
        $HOME/.local/bin/fix-whitespace --check
