name: Whitespace
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.10.1'
          cabal-version: '3.2'
      - name: Install fix-whitespace
        run: |
          cabal update
          cd src/fix-whitespace/
          cabal install
          cd ../..
      - name: Check the whitespace issue
        run: |
          $HOME/.cabal/bin/fix-whitespace --check
